metrics:
  wal_directory: "{{ grafana_agent_runtime_directory }}/prom-wal"
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
  configs:
    - name: "{{ ansible_hostname }}"
      host_filter: true
      scrape_configs:
        - job_name: "{{ ansible_hostname }}"
          scrape_interval: "15s"
          static_configs:
            - targets:
              - localhost:9100
      remote_write:
        - url: "{{ grafana_agent_metrics_endpoint }}/api/v1/push"
          headers:
            X-Scope-OrgID: "{{ grafana_agent_metrics_tenant_id }}"
logs:
  configs:
    - clients:
      - url: "{{ grafana_agent_logging_endpoint }}/loki/api/v1/push"
      name: "{{ ansible_hostname }}"
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: "{{ ansible_hostname }}/node_exporter"
          static_configs:
            - targets:
                - localhost
              labels:
                instance: {{ ansible_hostname }}
                __path__: /var/log/acmesh.log
                job: "{{ ansible_hostname }}/acmesh.log"
      target_config:
        sync_period: 10s
